<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FalconAuditService</AssemblyName>
    <RootNamespace>FalconAuditService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DiffPlex" Version="1.7.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="7.0.*" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.*" />
    <PackageReference Include="Serilog.AspNetCore" Version="7.0.*" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="7.0.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="5.0.*" />
    <PackageReference Include="Serilog.Sinks.EventLog" Version="3.1.*" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="FileClassificationRules.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="ParameterDescriptions.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
